### ISSUE TITLE
Browse/search functionality for available math research data

### ISSUE THREAD

**Issue by timconrad** [MaRDI4NFDI/MaRDIRoadmap#1]
As a researcher, I want to browse/search for all available mathematical research data relating to my problem with a unified frontend, so I can retrieve all information about my problem (algorithms, benchmarks, workflows, …) in one stop.

**Comment by physikerwelt** [comment]
We currently face the problem that the elastic search index is not up to date. Thus, I started index recreation today.
```bash
root@537dad6f93e3:/var/www/html/extensions/CirrusSearch/maintenance# php ForceSearchIndex.php
```
It does about 200 pages per second, which means the script will run 7 hours

**Comment by physikerwelt** [comment]
This is done
```
Indexed a total of 5731762 pages at 287/second
```
However, the job-queue has a backlog of 528 633 jobs.

**Comment by physikerwelt** [comment]
The burndown rate is really slow
```bash 
root@537dad6f93e3:/var/www/html/maintenance# time ./run runJobs.php --maxjobs 100 --nothrottle 10
real    1m34.728s
user    0m34.939s
sys     0m8.719s

**Comment by physikerwelt** [comment]
In total, we are still at 527 459 jobs. Which is about 1 job per second.

**Comment by physikerwelt** [comment]
let's try running 100 000 jobs with a DOP of 100
```bash
# Our custom function
cust_func(){
  echo "Do something $1 times..."
  docker compose exec -T wikibase /var/www/html/maintenance/run runJobs.php --maxjobs=1000
}
cd ~/portal-compose
# For loop 5 times
for i in {1..100}
do
        cust_func $i & # Put a function in the background
done

## Put all cust_func in the background and bash 
## would wait until those are completed 
## before displaying all done message
wait
echo "All done"

**Comment by physikerwelt** [comment]
`--maxjobs=1000` caused OOM exceptions. Thus, installing a crontab with `--maxjobs=7` that runs every minute. This brings us to 700 jobs per Minute, sufficient to process the remaining jobs during the night in the next (12 hours).

**Comment by physikerwelt** [comment]
The DB load pattern looks like it takes quite some time to select 700 in the big jobs table.
![image](https://github.com/MaRDI4NFDI/MaRDIRoadmap/assets/2777736/ba681f9c-ef7d-4484-a058-8a5bc328f827)
As the jobs don't finish all at the same time no specific write pattern is obvservable.

**Comment by physikerwelt** [comment]
We are don to 444 007 remaining jobs-- I also checked the usage pattern of the ES instance and the minute use pattern can be guessed as well.

![image](https://github.com/MaRDI4NFDI/MaRDIRoadmap/assets/2777736/e0c6dd49-6ef5-4e61-ab07-cc38bb1698da)

**Comment by physikerwelt** [comment]
Jobs are done. The search does work now.
