### ISSUE TITLE
Login with Google account (beta)

### ISSUE THREAD

**Issue by timconrad** [MaRDI4NFDI/MaRDIRoadmap#10]
**Describe the issue**

**Comment by physikerwelt** [comment]
The feature is currently hidden behind the 0 button.

![Screenshot 2023-02-21 at 21-32-16 Log in - MaRDI portal](https://user-images.githubusercontent.com/2777736/220452165-21004b8b-2a27-4493-bbe5-ffc7c19093f3.png)

**Comment by physikerwelt** [comment]
To test the feature you need to use the same email for the portal and your google account. In case you specified another email this can be reset by a portal admin via https://www.mediawiki.org/wiki/Manual:ResetUserEmail.php

**Comment by physikerwelt** [comment]
![Screenshot 2023-02-21 at 21-41-00 Log in - MaRDI portal](https://user-images.githubusercontent.com/2777736/220453592-09c88c11-3d94-4e86-bd7b-2164a5f9d531.png)

... the description looks much better now ...
