### ISSUE TITLE
MathML Formula feature

### ISSUE THREAD

**Issue by timconrad** [MaRDI4NFDI/MaRDIRoadmap#13]
**Describe the issue**

This is tracked in MediaWikis phabricator. 

- [Make 'only MathML rendering' interface available on MediaWiki/MediaWiki as a setting (without SVG rendering](https://phabricator.wikimedia.org/T310211)
- https://phabricator.wikimedia.org/T327386 : Create a Full Coverage Test for TexVC(PHP)
- https://phabricator.wikimedia.org/T329620 : Fix Chem support, to be clarified: partly covered atm when test MMLGenerationTexUtilTest.php is active
- https://phabricator.wikimedia.org/T327388 : Generate and Update reference MathML (from Mathoid/LaTeXML) for the current tests
- https://phabricator.wikimedia.org/T327391 : Fix TexVC parsetree related issues
- https://phabricator.wikimedia.org/T327393 : Implement a comparison algorithm which can compare different MathML outputs for automated testing
- https://phabricator.wikimedia.org/T328752 Implement a comparison algorithm which can compare different MathML for scientific results (to be clarified)
- https://phabricator.wikimedia.org/T327392 : Implement full coverage MathML parsing and mappings

**Comment by Hyper-Node** [comment]
Basic formula conversion is implemented in Math extension. 
Chemical formula parser is a work in progress.

**Comment by Hyper-Node** [comment]
Chemical formula parser done in final review phase, integration as preprocessor to texvc in progress

**Comment by Hyper-Node** [comment]
Validating all 44k formula for version 4.1.2 of mhchemParser in PHP, validating functionality is done.
