### ISSUE TITLE
CRAN metadata importer 

### ISSUE THREAD

**Issue by timconrad** [MaRDI4NFDI/MaRDIRoadmap#14]
Import metadata from https://cran.r-project.org/ and create corresponding wikibase entities to save the metadata in the MaRDI Knowledge Graph. Include daily update functionality to keep metadata up to date.

Imported metadata includes:
- Title
- Package version
- Date of publication
- Dependencies and imports 
- Authors (with ORCID and link Wikidata, when available)
- Maintainer
- License
- Related publications or arXiv preprints
- Related zenodo resources

**Comment by eloiferrer** [comment]
Libraries for the importer have been locally updated (elasticsearch, sqlalchemy, wikibaseintegrator). Bug fixing in process.

**Comment by eloiferrer** [comment]
Metadata for 800 R packages already published and available at the portal.
