### ISSUE TITLE
Portal user accounts

### ISSUE THREAD

**Issue by timconrad** [MaRDI4NFDI/MaRDIRoadmap#4]
As a general user, I want to be able to create an account and login to the system, so I can contribute my data to the portal.

**Comment by physikerwelt** [comment]
@timconrad This can be easily implemented. However, there will be an incredible amount of spam. I would therefore recommend against implementing this. Instead, we should wait for the [NFDI basic service IAM](https://www.dfn.de/dfn-aai-foerderung-des-nfdi-basisdienstes-iam/) to implement the general NFDI login.
