### ISSUE TITLE
Addition of new items to the knowledge graph

### ISSUE THREAD

**Issue by timconrad** [MaRDI4NFDI/MaRDIRoadmap#7]
As a maintainer of a mathematical repository or database, I want to integrate my (meta-)data into the portal | so that I can make my resources findable over the portal.

Comment: needs to be checked with editorial board, how this should be handled.

**Comment by eloiferrer** [comment]
A first version of an API client to directly write items to the knowledge graph in Python is available at: https://github.com/MaRDI4NFDI/mardiclient

**Comment by physikerwelt** [comment]
@M-dev-stack please count how many items have been added since the beta release
