### ISSUE TITLE
Integrate zbMATH Open data

### ISSUE THREAD

**Issue by timconrad** [MaRDI4NFDI/MaRDIRoadmap#8]
As a general user, I want to access the papers that are stored in zbMath, such that I can include them in my research.

**Comment by LizzAlice** [comment]
Identified data for alpha upload. Started working on code for import.

**Comment by LizzAlice** [comment]
Data dump was downloaded and processed, now starting test upload and bug fixing.

**Comment by LizzAlice** [comment]
Upload into portal started.

**Comment by physikerwelt** [comment]
@LizzAlice This is really great work, I am really happy to see this going live.

@rank-zero and I had a look at the first imported item ([portal-link](https://portal.mardi4nfdi.de/w/index.php?oldid=223954), [oai-pmh-link](https://oai.zbmath.org/v1/?verb=GetRecord&metadataPrefix=oai_zb_preview&identifier=oai%3Azbmath.org%3A1566037)). We might want to discuss, a few minor points before running the import for all 4.5M items, do we?

### 1 MSC

* Important for search
* Upstream Wikidata Property https://www.wikidata.org/wiki/Property:P3285
* Example in API response
```XML
<zbmath:classifications>
  <zbmath:classification>57R91</zbmath:classification>
  <zbmath:classification>55R91</zbmath:classification>
  <zbmath:classification>55R50</zbmath:classification>
  <zbmath:classification>57S25</zbmath:classification>
  <zbmath:classification>57R25</zbmath:classification>
  <zbmath:classification>55R25</zbmath:classification>
  <zbmath:classification>22A25</zbmath:classification>
</zbmath:classifications>
```

### 2 Reviews
* important for fulltext serach
* not part of fulltext
* example API result
```XML
<zbmath:review>
  <zbmath:review_language>English</zbmath:review_language>
  <zbmath:review_sign>Vladimir L. Popov (Moskva)</zbmath:review_sign>
  <zbmath:review_text>
Let \(G\) be a topological group, \(M\) be a unitary representation space of \(G\), and \(S(M)\) be the unit sphere of \(M\). Let \(W_k(M)\) be the Stiefel manifold of unitary \(k\)-frames on \(M\). The projection map \(W_k(M)\rightarrow S(M)\) sending a unitary \(k\)-frame \((u_1,\ldots,u_k)\) to \(u_k\) is \(G\)-equivariant. The author gives some necessary and sufficient conditions for the existence of a \(G\)-equivariant cross section of \(W_k(M)\) for certain finite group actions, under mild fixed point conditions. When \(G\) acts trivially, this is answered in [\textit{M. F. Atiyah} and \textit{J. A. Todd}, Proc. Camb. Philos. Soc. 56, 342-353 (1960; Zbl 0109.16102); \textit{J. F. Adams} and \textit{G. Walker}, ibid. 61, 81-103 (1965; Zbl 0142.40903)].
  </zbmath:review_text>
  <zbmath:review_type>review</zbmath:review_type>
  <zbmath:reviewer>1355</zbmath:reviewer>
  <zbmath:reviewer_id>popov.vladimir-leonidovich</zbmath:reviewer_id>
</zbmath:review>
```

### 3. DE Number
* the zbl-identifier is not available for all records and less stable compared to the DE number. Therefore it would be good to keep that as provenance information
* Example data `<identifier>oai:zbmath.org:1566037</identifier>`

### 4. Keywords
* good for search
* example data 
```XML
<zbmath:keywords>
  <zbmath:keyword>complex Stiefel manifolds</zbmath:keyword>
  <zbmath:keyword>equivariant fibre spaces</zbmath:keyword>
  <zbmath:keyword>equivariant cross section</zbmath:keyword>
</zbmath:keywords>
```

### References

Also interesting for graph search queries. However, to establish links, this needs to be done in pass2.

Are there other examples we should look at to see if we have further ideas?

**Comment by LizzAlice** [comment]
Isn't that the wrong MSC property? As far as I know, zbMath uses MSC2020, but the wikidata property is for MSC2010

**Comment by physikerwelt** [comment]
> Isn't that the wrong MSC property? As far as I know, zbMath uses MSC2020, but the wikidata property is for MSC2010

It is almost exactly the same. There is an update procedure from MSC 2010 to MSC202. We can even manually update all MSC classifications on Wikidata.

**Comment by LizzAlice** [comment]
Concerning the other fields:
2.) Do you only mean the review text, or also the other fields? What exactly is a review?
3.) So the DE number would be the whole thing from oai to 37?
4.) With which property would you mark keywords?

**Comment by LizzAlice** [comment]
> > Isn't that the wrong MSC property? As far as I know, zbMath uses MSC2020, but the wikidata property is for MSC2010
> 
> It is almost exactly the same. There is an update procedure from MSC 2010 to MSC202. We can even manually update all MSC classifications on Wikidata.

Yes, but using this property would be wrong anyway, right? If anything, we would have to create one for 2020

**Comment by physikerwelt** [comment]
> Yes, but using this property would be wrong anyway, right? If anything, we would have to create one for 2020
No, I think someone should update the description of the property in Wikidata. Papers are usually classified when they come out with the MSC version that is current at that time. So mentioning the current version in the MSC is a bit confusing.

**Comment by LizzAlice** [comment]
> > Yes, but using this property would be wrong anyway, right? If anything, we would have to create one for 2020
> 
> No, I think someone should update the property description in Wikidata. Papers are usually classified when they come out with the MSC version that is current at that time. So mentioning the current version in the MSC is a bit confusing.

As that someone should probably be someone with a bit of renown in that community, could you do that?

**Comment by physikerwelt** [comment]
> Concerning the other fields: 

2) One needs to think about that. For search the review_text is important.

3) the prefix is always the same, so it is sufficient to store `1566037`

4) One needs to think about that as well.

**Comment by physikerwelt** [comment]
2) I feel we should also add the author, which again creates a linking problem as QID for the author might not have been created.

3) You can re-use the name from https://zenodo.org/record/5884600 

zbmath-id Unique identifier from zbMATH Open. Prefix with https://zbmath.org/ to visit additional information on the article. For example, 5635019 is associated with https://zbmath.org/5635019

4) What would be the data-type of the keyword? Is it different from other keywords, for example, those used in the CRAN import?

**Comment by physikerwelt** [comment]
To make the review-text easily readable, we would need to use Wikitext as a format, which is not currently possible in Wikibase (https://phabricator.wikimedia.org/T141764). Thus one might want to create one MediaWiki page for each article.

**Comment by physikerwelt** [comment]
Examples of articles with two reviews.
https://zbmath.org/1342.78017
https://zbmath.org/1173.94002
https://zbmath.org/0705.11075
https://zbmath.org/0681.32017

**Comment by LizzAlice** [comment]
Added review, msc, de number and keywords a few weeks ago;
now over 600,000 papers uploaded

**Comment by LizzAlice** [comment]
Now over 1 million papers uploaded

**Comment by LizzAlice** [comment]
Now over 1.5 million paper records uploaded.

**Comment by LizzAlice** [comment]
First run completed, about 1.7 million papers uploaded. A lot of papers were not uploaded because the title does not get shown via the zbmath api because of licensing conflicts. Working on second run which gets the title from crossref, if a doi is given.

**Comment by physikerwelt** [comment]
To have a complete link graph, it would be great to seed all papers in the second run. We could just use a pseudo title?

**Comment by LizzAlice** [comment]
It seems to me that this would just create potential, hard to identify duplicates of papers from other sources. We could do another run, if the licensing conflicts ever get resolved.

**Comment by LizzAlice** [comment]
Also, sometimes the references are not available anyway because of licensing conflicts (might be the same ones?)

**Comment by LizzAlice** [comment]
Since there are 1,427,910 papers without title and without doi, they will be uploaded without label or with a replacement label.

**Comment by physikerwelt** [comment]
At least for the link graph it would be better to include them without a title.

**Comment by LizzAlice** [comment]
Second run that also uploads papers without title and queries titles from doi if possible has been started.

**Comment by LizzAlice** [comment]
3 million uploaded papers.

**Comment by LizzAlice** [comment]
More than 3.5 million uploaded papers.

**Comment by LizzAlice** [comment]
More than 4 million uploaded papers.

**Comment by LizzAlice** [comment]
Upload finished, there are now about 4.5 million uploaded papers. 
Now debugging and fixing cause for ca. 90000 failed papers.
